pictures/urls.py
from django.urls import path
from . import views

app_name = 'pictures'

urlpatterns = [
    # トップ画面
    path('', views.IndexView.as_view(), name='index'),

    # 詳細画面
    path('pictures/<int:pk>/', views.DetailView.as_view(), name='detail'),

    # ファイルアップロード用
    # path('pictures/<int:pk>/upload/', views.Upload.as_view(), name='upload'),
    path('pictures/<int:pk>/upload/', views.uploadImage, name='upload'),  # ConoHaオブジェクトストレージに登録
    path('pictures/<int:pk>/upload_complete/', views.UploadComplete.as_view(), name='upload_complete'),
]

works/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pictures.urls')), # ホームURL
    path('accounts/', include('django.contrib.auth.urls')), # ログイン認証
]

pictures/models.py
from django.db import models
from django.urls import reverse


class Work(models.Model):
    """作品モデル"""
    class Meta:
        db_table = 'work'

    name = models.CharField(verbose_name='作品名', max_length=255)
    memo = models.CharField(verbose_name='メモ', max_length=255, default='', blank=True)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url(self):
        return reverse('pictures:index')


class Image(models.Model):
    """イメージモデル"""
    class Meta:
        db_table = 'image'

    work = models.ForeignKey(Work, verbose_name='作品', on_delete=models.PROTECT)
    image = models.ImageField(upload_to="image/", verbose_name='イメージ')
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return self.work.name + ":" + str(self.data_datetime)

pictures/forms.py
from django import forms
import os

VALID_EXTENSIONS = ['.jpg']


class UploadFileForm(forms.Form):
    image = forms.ImageField()

    def clean_image(self):
        image = self.cleaned_data['image']
        extension = os.path.splitext(image.name)[1]  # 拡張子を取得
        if not extension.lower() in VALID_EXTENSIONS:
            raise forms.ValidationError('jpgファイルを選択してください！')
        return image  # viewsでcleaned_dataを参照するためreturnする

pictures/views.py
from django.shortcuts import redirect
from django.views import generic
from .models import Work, Image
from django.contrib.auth.mixins import LoginRequiredMixin
import logging
from .forms import UploadFileForm
from django.views.generic.edit import FormView
import requests
import json
from works import settings
import os
from django.shortcuts import render

logger = logging.getLogger('development')

# アップロードした画像を保存するディレクトリ
UPLOAD_IMG_DIR = settings.MEDIA_ROOT + '/image/'

# オブジェクトストレージ接続パラメータ
USER_NAME = "gncu00000000"  # ユーザー名
PASSWORD = "passpasspass"  # パスワード
TENANT_ID = "9999999999999999999999999"  # テナントID
URL = 'https://identity.tyo2.conoha.io/v2.0/tokens'  # トークン取得用URL
OBJECT_STORAGE = 'https://object-storage.tyo2.conoha.io/v1/nc_9999999999999999999999999999'  # オブジェクトストレージURL
CONTAINER = 'sample1'  # コンテナ名


# 一覧画面
class IndexView(LoginRequiredMixin, generic.ListView):
    model = Work
    paginate_by = 5
    ordering = ['-updated_at']
    template_name = 'pictures/index.html'


# 詳細画面
class DetailView(generic.DetailView):
    model = Work
    template_name = 'pictures/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.request.session.modified = True  # セッション更新
        context['work_pk'] = self.kwargs['pk']

        return context


# # ファイルアップロード
# class Upload(FormView):
#     template_name = 'pictures/upload.html'
#     form_class = UploadFileForm
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         form = self.get_form()
#         context = {
#             'work_pk': self.kwargs['pk'],
#             'form': form,
#         }
#         return context
#
#     def form_valid(self, form):
#
#         image = Image()  # DBへの保存
#         image.work_id = self.kwargs['pk']  # 作品ID
#         image.image = form.cleaned_data['image']  # アップロードしたイメージパス
#         image.save()
#
#         return redirect('pictures:upload_complete', self.kwargs['pk'])  # アップロード完了画面にリダイレクト


def getToken(userName, password, tenantId, url):
    """
    tokenの取得
    :param userName:
    :param password:
    :param tenantId:
    :param url:
    :return:
    """

    headers = {
        'Accept': 'application/json',
    }

    data = '{"auth":{"passwordCredentials":{"username":"%s","password":"%s"},"tenantId":"%s"}}' % (
    userName, password, tenantId)

    response = requests.post(url, headers=headers, data=data)
    data = response.json()

    return json.dumps(data["access"]["token"]["id"], indent=4)


def uploadObject(token, path, objectStorageUrl, container, fileName):
    """
    オブジェクトのアップロード
    :param token:
    :param path:
    :param objectStorageUrl:
    :param container:
    :param fileName:
    :return:
    """

    headers = {
        'Accept': 'application/json',
        'X-Auth-Token': token,
    }

    with open(path, 'rb') as image:
        response = requests.put(objectStorageUrl + '/' + container + '/' + fileName, headers=headers, data=image)

    return response


def handle_uploaded_image(upload_image, pk):
    """
    アップロードされた画像のハンドル
    :param upload_image:
    :param pk:
    :return:
    """
    # アップロードファイルを一旦保存する。
    path = os.path.join(UPLOAD_IMG_DIR, upload_image.name)
    with open(path, 'wb+') as destination:
        for chunk in upload_image.chunks():
            destination.write(chunk)

    # オブジェクトストレージにアップロードする。
    token = getToken(USER_NAME, PASSWORD, TENANT_ID, URL).replace('\"', '')  # tokenの取得

    fileName = str(upload_image.name)  # ファイル名

    result = uploadObject(token, path, OBJECT_STORAGE, CONTAINER, fileName)  # オブジェクトのアップロード

    if result.status_code == 201:  # アップロード成功の場合

        image = Image()  # DBへの保存
        image.work_id = pk  # 作品ID
        image.image = OBJECT_STORAGE + '/' + CONTAINER + '/' + fileName  # アップロードしたイメージパス
        image.save()

        # アップロードしたファイルを削除する
        os.remove(path)

    else:  # アップロード失敗の場合
        logger.warning('オブジェクトのアップロードに失敗しました。')


def uploadImage(request, pk):
    """
    画像のアップロード
    :param request:
    :param pk:
    :return:
    """
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():

            handle_uploaded_image(request.FILES['image'], pk)  # アップロードされた画像のハンドル
            return redirect('pictures:upload_complete', pk)  # アップロード完了画面にリダイレクト
    else:
        form = UploadFileForm()
    return render(request, 'pictures/upload.html', {'form': form})


class UploadComplete(FormView):
    """
    ファイルアップロード完了
    """
    template_name = 'pictures/upload_complete.html'
    form_class = UploadFileForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.request.session.modified = True  # セッション更新
        context['work_pk'] = self.kwargs['pk']

        return context

pictures/templates/pictures/1/test.html
<h2>犬です！！</h2>

pictures/templates/pictures/2/test.html
<h2>狸です！！</h2>

pictures/templates/pictures/3/test.html
<h2>アライグマです！！</h2>

pictures/templates/pictures/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <section class="">
        {{ object.memo|linebreaksbr }}
    </section>

    <!-- テンプレート読み込み -->
    {% with pk=object.pk|slugify %}
        {% with template="pictures/"|add:pk|add:"/test.html" %}
            {% include template %}
        {% endwith %}
    {% endwith %}

    <section>
        <p><a href="javascript:history.back()">&lt; Back</a></p>
    </section>
{% endblock %}

pictures/templates/pictures/index.html
{% extends 'base.html' %}

{% block content %}

<h1>My Works</h1>

<section class="">
    <ul>
        {% for work in object_list %}
        <li>
            <h2><a href="{% url 'pictures:detail' work.pk %}">{{ work.name }}</a></h2>
            <p>{{ work.memo }}</p>
        </li>
        {% empty %}
        <li class="no-post">
            <p>No work yet.</p>
        {% endfor %}
    </ul>
</section>

{% if is_paginated %}
<section class="pagination">
    <ul>
        <li>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt; Prev</a>
            {% else %}
            &lt;&lt; Prev
            {% endif %}
        </li>
        <li>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &gt;&gt;</a>
            {% else %}
            Next &gt;&gt;
            {% endif %}
        </li>
    </ul>
</section>
{% endif %}
{% endblock %}

pictures/templates/pictures/upload.html
<!-- upload.html -->
{% extends 'base.html' %}

{% block content %}

<h1>アップロード サンプル</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    {% for field in form %}
    <div class="form-group form-inline">
        <div class="col-md-8">
            {{ field }}
        </div>
    </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit">アップロード</button>
    </div>
</form>

    <section>
        <p><a href="javascript:history.back()">&lt; Back</a></p>
    </section>

{% endblock %}

pictures/templates/pictures/upload_complete.html
{% extends 'base.html' %}

{% block content %}

<h1>アップロード完了</h1>

<button type="submit" onClick="javascript:history.back();">戻る</button>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}My ポートフォリオ</title>
    </head>
    <body>
    <div class="container">
        <header>
            <p class="site-name"><a href="{% url 'pictures:index' %}">作品ポートフォリオ</a></p>
            <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" class="logout">ログアウト</a></li>
                    {% if work_pk %}
                        <li><a href="{% url 'pictures:detail' work_pk %}">作品詳細</a></li>
                        <li><a href="{% url 'pictures:upload' work_pk %}">ファイルアップロード</a></li>
                    {% else %}
                        <li><a href="{% url 'pictures:index' %}">作品一覧</a></li>
                    {% endif %}
                {% else %}
                    <li><a href="{% url 'login' %}" class="login">ログイン</a></li>
                {% endif %}
            </ul>
        </nav>
        </header>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    </body>
</html>